default:
  image: ubuntu:18.04


stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - apt update
    - apt-get install -y software-properties-common
    - add-apt-repository ppa:george-edison55/cmake-3.x
    - apt-get update
    - apt install -y cmake
    - apt upgrade -y
    - cmake .
    - make
    - echo "Build complete."

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running tests..."
    - ./build/tests/Test
    - echo "Test complete."

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Nowhere to deploy"

